version: '3.7'

services:

    db:
        
        image: mongo:latest
        container_name: mongo
        ports:
        - "27017:27017"
        environment:
        - MONGODB_ROOT_PASSWORD=password
        - MONGODB_USERNAME=admin
        - MONGODB_PASSWORD=password
        - MONGODB_DATABASE=test
        volumes:
        - /data/db:/bitnami

    api:
        container_name: crypto_server
        build:
            context: .
            dockerfile: Dockerfile
        command: ["go", "run", "main.go"]
        depends_on:
            - db
        volumes:
            - .:/usr/src/app
        ports:
            - "8080:8080"
        restart: always
        

