version: '3.7'

services:

    db:
        
        image: mongo:5.0.3
        container_name: mongo
        ports:
        - "27017:27017"
        environment:
        - MONGODB_ROOT_PASSWORD=password
        - MONGODB_USERNAME=admin
        - MONGODB_PASSWORD=password
        - MONGODB_DATABASE=test
        volumes:
        - ./db/:/data/db/
        - ./backup/:/backup/
        restart: always

    api:
        container_name: crypto_server
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - ./:/app/

        depends_on:
            - db
        # ports:
        #     - "8080:8080"
        restart: always
    
    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./ssl/:/etc/nginx/ssl/
        ports:
        - 8080:8080
        depends_on:
        - api
        

